"""Import all schemas."""

from app.schemas.auth import (
    UserRegister,
    UserLogin,
    TokenRefresh,
    TokenResponse,
    UserResponse,
    UserMeResponse,
)
from app.schemas.user import (
    UserBase,
    UserUpdate,
    UserListItem,
    UserDetail,
    UserListResponse,
    PaginationMeta,
)
from app.schemas.campaign import (
    Campaign,
    CampaignCreate,
    CampaignUpdate,
    CampaignWithAds,
    CampaignList,
    CampaignAudienceTargeting,
    CampaignAudienceTargetingCreate,
)
from app.schemas.ad import (
    AdBase,
    AdCreate,
    AdUpdate,
    AdListItem,
    AdDetail,
    AdListResponse,
    TimeSlotBase,
    TimeSlotCreate,
    TimeSlotResponse,
    ContentRatingBase,
    ContentRatingCreate,
    ContentRatingResponse,
)
from app.schemas.advertiser import (
    AdvertiserBase,
    AdvertiserCreate,
    AdvertiserUpdate,
    AdvertiserListItem,
    AdvertiserDetail,
    AdvertiserListResponse,
    ContactBase,
    ContactCreate,
    ContactResponse,
    BankAccountBase,
    BankAccountCreate,
    BankAccountResponse,
)

__all__ = [
    # Auth
    "UserRegister",
    "UserLogin",
    "TokenRefresh",
    "TokenResponse",
    "UserResponse",
    "UserMeResponse",
    # User
    "UserBase",
    "UserUpdate",
    "UserListItem",
    "UserDetail",
    "UserListResponse",
    "PaginationMeta",
    # Campaign
    "Campaign",
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignWithAds",
    "CampaignList",
    "CampaignAudienceTargeting",
    "CampaignAudienceTargetingCreate",
    # Ad
    "AdBase",
    "AdCreate",
    "AdUpdate",
    "AdListItem",
    "AdDetail",
    "AdListResponse",
    "TimeSlotBase",
    "TimeSlotCreate",
    "TimeSlotResponse",
    "ContentRatingBase",
    "ContentRatingCreate",
    "ContentRatingResponse",
    # Advertiser
    "AdvertiserBase",
    "AdvertiserCreate",
    "AdvertiserUpdate",
    "AdvertiserListItem",
    "AdvertiserDetail",
    "AdvertiserListResponse",
    "ContactBase",
    "ContactCreate",
    "ContactResponse",
    "BankAccountBase",
    "BankAccountCreate",
    "BankAccountResponse",
]
